"""
src/pipeline/paths.py
---------------------
Default path constants for the GF Updater V3 pipeline.

These are the *default* values.  run_orchestrator.py may override some of
them on main's module namespace before calling run_pipeline().  Because of
that, run_pipeline reads paths from the calling module (main), not from
this module.  This file exists so the definitions live in one place and
main.py can do ``from pipeline.paths import *`` to populate its namespace.
"""

from pathlib import Path

# ─────────────────────────────────────────────────────────────
# Resolve relative to main.py (two levels up from this file)
# ───────���─────────────────────────────────────────────────────
_MAIN_DIR = Path(__file__).resolve().parent.parent.parent

BASE_DIR          = _MAIN_DIR
INPUT_DIR         = BASE_DIR / "input"
OUTPUT_DIR        = BASE_DIR / "output"
INTERMEDIATE_DIR  = OUTPUT_DIR / "intermediate"
DEBUG_DIR         = OUTPUT_DIR / "debug"
RUNS_DIR          = BASE_DIR / "runs"
DATA_DIR          = BASE_DIR / "data"

# ── Database paths ────────────────────────────────────────────
REPORT_MEMORY_DB = str(DATA_DIR / "report_memory.db")
RUN_MEMORY_DB    = str(DATA_DIR / "run_memory.db")

# ── Input paths ───────────────────────────────────────────────
CONSULTANT_REPORTS_ROOT = INPUT_DIR / "consultant_reports"
CONSULTANT_MATCH_REPORT = OUTPUT_DIR / "consultant_match_report.xlsx"
GED_FILE      = INPUT_DIR / "GED_export.xlsx"
GF_FILE       = INPUT_DIR / "Grandfichier_v3.xlsx"
FLAT_GED_FILE = INTERMEDIATE_DIR / "FLAT_GED.xlsx"  # generated by flat_ged_runner; not user-facing input

# Feature flag controlling which GED read path run_pipeline() uses.
#
# Module-level default: "raw"  (safe fallback for direct / standalone callers
#   that have not built a Flat GED artifact).
#
# Runtime behaviour via run_orchestrator.py (i.e. every normal production run):
#   the orchestrator always builds the Flat GED first, then overrides this to
#   "flat" on the main-module namespace before calling run_pipeline().
#   "raw" is only active in production when GFUP_FORCE_RAW=1 is set in the
#   environment (explicit developer escape hatch).
#
# Do NOT change this default to "flat" — direct callers that skip the
# orchestrator have no Flat GED artifact and would crash.
FLAT_GED_MODE = "raw"

# ── Primary output paths ─────────────────────────────────────
OUTPUT_GF                      = OUTPUT_DIR / "GF_V0_CLEAN.xlsx"
OUTPUT_DISCREPANCY             = OUTPUT_DIR / "DISCREPANCY_REPORT.xlsx"
OUTPUT_DISCREPANCY_REVIEW      = OUTPUT_DIR / "DISCREPANCY_REVIEW_REQUIRED.xlsx"
OUTPUT_ANOMALY                 = OUTPUT_DIR / "ANOMALY_REPORT.xlsx"
OUTPUT_AUTO_RESOLUTION         = OUTPUT_DIR / "AUTO_RESOLUTION_LOG.xlsx"
OUTPUT_IGNORED                 = OUTPUT_DIR / "IGNORED_ITEMS_LOG.xlsx"

# ── Diagnosis outputs (Part E) ───────────────────────────────
OUTPUT_MISSING_GED_DIAGNOSIS   = OUTPUT_DIR / "MISSING_IN_GED_DIAGNOSIS.xlsx"
OUTPUT_MISSING_GED_TRUE        = OUTPUT_DIR / "MISSING_IN_GED_TRUE_ONLY.xlsx"
OUTPUT_MISSING_GF_DIAGNOSIS    = OUTPUT_DIR / "MISSING_IN_GF_DIAGNOSIS.xlsx"
OUTPUT_MISSING_GF_TRUE         = OUTPUT_DIR / "MISSING_IN_GF_TRUE_ONLY.xlsx"

# ── Reconciliation outputs (Patch F) ─────────────────────────
OUTPUT_RECONCILIATION_LOG      = OUTPUT_DIR / "RECONCILIATION_LOG.xlsx"
OUTPUT_RECONCILIATION_SUMMARY  = DEBUG_DIR  / "reconciliation_summary.xlsx"

# ── Insert log ────────────────────────────────────────────────
OUTPUT_INSERT_LOG              = OUTPUT_DIR / "INSERT_LOG.xlsx"

# ── New submittal + consultant outputs ────────────────────────
OUTPUT_NEW_SUBMITTAL_ANALYSIS  = OUTPUT_DIR / "NEW_SUBMITTAL_ANALYSIS.xlsx"
OUTPUT_NEW_SUBMITTAL_SUMMARY   = DEBUG_DIR  / "new_submittal_summary.xlsx"
OUTPUT_CONSULTANT_REPORTS_WB   = OUTPUT_DIR / "consultant_reports.xlsx"
OUTPUT_GF_STAGE1               = OUTPUT_DIR / "GF_consultant_enriched_stage1.xlsx"
OUTPUT_GF_STAGE2               = OUTPUT_DIR / "GF_consultant_enriched_stage2.xlsx"
OUTPUT_GF_TEAM_VERSION         = OUTPUT_DIR / "GF_TEAM_VERSION.xlsx"
OUTPUT_SUSPICIOUS_ROWS         = OUTPUT_DIR / "SUSPICIOUS_ROWS_REPORT.xlsx"

# ── Versioning ────────────────────────────────────────────
RUN_MEMORY_CORE_VERSION = "P1"
