"""
bootstrap_run_zero.py
---------------------
One-time script that promotes the currently trusted output state into Run 0
(the baseline truth for the run-history subsystem).

Run 0 is:
  - dated 2026-04-10 (the established baseline date for this project)
  - run_type = BASELINE
  - is_baseline = True
  - root_run_number = 0
  - immutable: later runs derive from it

What this script does:
  1. Initialise run_memory.db
  2. Refuse to run again unless --force is passed (idempotency guard)
  3. Create Run 0 record in the DB
  4. Scan existing output/ and output/debug/ artifacts
  5. Copy them into runs/run_0000/ (and runs/run_0000/debug/)
  6. Register each artifact in run_artifacts
  7. Register known input provenance (GED, GF, Mapping)
  8. Mark Run 0 as current
  9. Print a clear summary

Usage:
    cd "GF updater v3"
    python scripts/bootstrap_run_zero.py
    python scripts/bootstrap_run_zero.py --force    # re-run if Run 0 already exists
    python scripts/bootstrap_run_zero.py --db-path data/run_memory.db
    python scripts/bootstrap_run_zero.py --root-dir /path/to/project
"""

import argparse
import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

for _stream_name in ("stdout", "stderr"):
    _stream = getattr(sys, _stream_name, None)
    if hasattr(_stream, "reconfigure"):
        try:
            _stream.reconfigure(encoding="utf-8", errors="replace")
        except Exception:
            pass

# ---------------------------------------------------------------------------
# Path setup — allows running from project root or from scripts/ directory
# ---------------------------------------------------------------------------

_SCRIPT_DIR   = Path(__file__).resolve().parent
_PROJECT_ROOT = _SCRIPT_DIR.parent
_SRC_DIR      = _PROJECT_ROOT / "src"

sys.path.insert(0, str(_SRC_DIR))

from run_memory import (
    init_run_memory_db,
    update_run_metadata,
    finalize_run_success,
    mark_run_current,
    register_run_input,
    register_run_artifact,
    copy_artifact_to_run_dir,
    get_run_dir,
    sha256_file,
    list_runs,
    list_run_artifacts,
    invalidate_descendant_runs,
)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# The canonical baseline date for the project (not necessarily today)
BASELINE_DATE = "2026-04-10"
BASELINE_LABEL = "Run 0 - baseline 2026-04-10"
BASELINE_NOTES = (
    "Bootstrap: trusted output state as of 2026-04-10. "
    "Generated by bootstrap_run_zero.py. "
    "This is the immutable root for all future runs."
)

# Artifact catalog: (source_relative_path, artifact_type, format, is_debug)
# source_relative_path is relative to project root
# is_debug=True → copied to runs/run_0000/debug/
_ARTIFACT_CATALOG = [
    # ── Primary outputs ─────────────────────────────────────────────────────
    ("output/GF_V0_CLEAN.xlsx",                   "FINAL_GF",                    "xlsx", False),
    ("output/DISCREPANCY_REPORT.xlsx",             "DISCREPANCY_REPORT",          "xlsx", False),
    ("output/DISCREPANCY_REVIEW_REQUIRED.xlsx",    "DISCREPANCY_REVIEW_REQUIRED", "xlsx", False),
    ("output/ANOMALY_REPORT.xlsx",                 "ANOMALY_REPORT",              "xlsx", False),
    ("output/AUTO_RESOLUTION_LOG.xlsx",            "AUTO_RESOLUTION_LOG",         "xlsx", False),
    ("output/IGNORED_ITEMS_LOG.xlsx",              "IGNORED_ITEMS_LOG",           "xlsx", False),
    ("output/INSERT_LOG.xlsx",                     "INSERT_LOG",                  "xlsx", False),
    ("output/RECONCILIATION_LOG.xlsx",             "RECONCILIATION_LOG",          "xlsx", False),
    ("output/MISSING_IN_GED_DIAGNOSIS.xlsx",       "MISSING_IN_GED_DIAGNOSIS",    "xlsx", False),
    ("output/MISSING_IN_GED_TRUE_ONLY.xlsx",       "MISSING_IN_GED_TRUE",         "xlsx", False),
    ("output/MISSING_IN_GF_DIAGNOSIS.xlsx",        "MISSING_IN_GF_DIAGNOSIS",     "xlsx", False),
    ("output/MISSING_IN_GF_TRUE_ONLY.xlsx",        "MISSING_IN_GF_TRUE",          "xlsx", False),
    ("output/NEW_SUBMITTAL_ANALYSIS.xlsx",         "NEW_SUBMITTAL_ANALYSIS",      "xlsx", False),
    ("output/consultant_match_report.xlsx",        "CONSULTANT_MATCH_REPORT",     "xlsx", False),
    ("output/consultant_reports.xlsx",             "CONSULTANT_REPORTS",          "xlsx", False),
    ("output/GF_TEAM_VERSION.xlsx",                "GF_TEAM_VERSION",             "xlsx", False),
    ("output/GF_consultant_enriched_stage1.xlsx",  "CONSULTANT_ENRICHED_STAGE1",  "xlsx", False),
    ("output/GF_consultant_enriched_stage2.xlsx",  "CONSULTANT_ENRICHED_STAGE2",  "xlsx", False),
    ("output/SUSPICIOUS_ROWS_REPORT.xlsx",         "SUSPICIOUS_ROWS_REPORT",      "xlsx", False),
    # ── Debug outputs ────────────────────────────────────────────────────────
    ("output/debug/routing_summary.xlsx",          "DEBUG_ROUTING_SUMMARY",       "xlsx", True),
    ("output/debug/exclusion_summary.xlsx",        "DEBUG_EXCLUSION_SUMMARY",     "xlsx", True),
    ("output/debug/reconciliation_summary.xlsx",   "DEBUG_RECONCILIATION_SUMMARY","xlsx", True),
    ("output/debug/missing_in_ged_summary.xlsx",   "DEBUG_MISSING_IN_GED_SUMMARY","xlsx", True),
    ("output/debug/missing_in_gf_summary.xlsx",    "DEBUG_MISSING_IN_GF_SUMMARY", "xlsx", True),
    ("output/debug/coarse_groups.xlsx",            "DEBUG_COARSE_GROUPS",         "xlsx", True),
    ("output/debug/family_clusters.xlsx",          "DEBUG_FAMILY_CLUSTERS",       "xlsx", True),
    ("output/debug/lifecycle_resolution.xlsx",     "DEBUG_LIFECYCLE_RESOLUTION",  "xlsx", True),
    ("output/debug/discrepancy_sample.xlsx",       "DEBUG_DISCREPANCY_SAMPLE",    "xlsx", True),
    ("output/debug/gf_duplicates.xlsx",            "DEBUG_GF_DUPLICATES",         "xlsx", True),
    ("output/debug/gf_sheet_schema.xlsx",          "DEBUG_GF_SHEET_SCHEMA",       "xlsx", True),
    ("output/debug/new_submittal_summary.xlsx",    "DEBUG_NEW_SUBMITTAL_SUMMARY", "xlsx", True),
]

# Known input files (relative to project root)
_INPUT_CATALOG = [
    ("input/GED_export.xlsx",       "GED",     "GED_export.xlsx"),
    ("input/Grandfichier_v3.xlsx",  "GF",      "Grandfichier_v3.xlsx"),
    ("input/Mapping.xlsx",          "MAPPING", "Mapping.xlsx"),
]


# ---------------------------------------------------------------------------
# Bootstrap logic
# ---------------------------------------------------------------------------

def _hash_file_safe(path: Path) -> str | None:
    """Hash a file; return None if it cannot be read."""
    try:
        return sha256_file(str(path))
    except (OSError, PermissionError):
        return None


def run_bootstrap_zero(
    db_path: str | None = None,
    root_dir: str | None = None,
    force: bool = False,
) -> None:
    root = Path(root_dir).resolve() if root_dir else _PROJECT_ROOT

    if db_path is None:
        db_path = str(root / "data" / "run_memory.db")

    print("=" * 64)
    print("GF Updater V3 — Bootstrap Run 0")
    print("=" * 64)
    print(f"  DB path    : {db_path}")
    print(f"  Root dir   : {root}")
    print(f"  Baseline   : {BASELINE_DATE}")
    print()

    # ── Step 1: Initialise DB ─────────────────────────────────────────────────
    print("[1/5] Initialising run_memory.db ...")
    init_run_memory_db(db_path)
    print("  DB ready.")

    # ── Step 2: Idempotency guard ─────────────────────────────────────────────
    print("\n[2/5] Checking existing runs ...")
    existing = list_runs(db_path)
    if not existing.empty:
        print(f"  Found {len(existing)} existing run(s):")
        for _, row in existing.iterrows():
            print(
                f"    Run {row['run_number']:4d}  "
                f"{row['run_type']:12s}  "
                f"is_baseline={row['is_baseline']}  "
                f"{row.get('run_label', '')}"
            )
        if not force:
            print()
            print("  ⚠️  Run 0 (or other runs) already exist.")
            print("  Run with --force to re-bootstrap (will overwrite Run 0 record).")
            return
        else:
            print("  --force passed: re-bootstrapping Run 0.")

    # ── Step 3: Create Run 0 record ───────────────────────────────────────────
    print("\n[3/5] Creating Run 0 record ...")

    # Use BASELINE_DATE as created_at for Run 0's record
    # (overrides the usual _now_utc() by directly inserting)
    import sqlite3, os
    os.makedirs(Path(db_path).parent, exist_ok=True)
    run_dir  = get_run_dir(str(root), 0)
    if force and Path(run_dir).exists():
        shutil.rmtree(run_dir)
    with sqlite3.connect(db_path) as conn:
        conn.execute("PRAGMA journal_mode=WAL")
        conn.execute("PRAGMA foreign_keys=ON")
        if force:
            conn.execute("DELETE FROM run_inputs WHERE run_number = 0")
            conn.execute("DELETE FROM run_artifacts WHERE run_number = 0")
            conn.execute("DELETE FROM run_corrections WHERE source_run_number = 0")
            conn.execute("DELETE FROM run_invalidation_log WHERE invalidated_by_run_number = 0")
        conn.execute("DELETE FROM runs WHERE run_number = 0")
        conn.execute(
            """
            INSERT INTO runs (
                run_number, run_label, created_at, run_type,
                parent_run_number, root_run_number, based_on_run_number,
                is_baseline, is_current, is_stale, notes,
                core_version, status, completed_at, error_message
            ) VALUES (0, ?, ?, 'BASELINE', NULL, 0, NULL, 1, 0, 0, ?, ?, 'STARTED', NULL, NULL)
            """,
            (BASELINE_LABEL, f"{BASELINE_DATE}T00:00:00+00:00", BASELINE_NOTES, "P1"),
        )
    print(f"  Run 0 created: {BASELINE_LABEL}")

    # ── Step 4: Scan artifacts, copy, and register ────────────────────────────
    print("\n[4/5] Scanning and registering artifacts ...")

    Path(run_dir).mkdir(parents=True, exist_ok=True)
    Path(run_dir, "debug").mkdir(parents=True, exist_ok=True)

    registered  = 0
    skipped_missing = 0
    input_count = 0

    for rel_path, artifact_type, fmt, is_debug in _ARTIFACT_CATALOG:
        src = root / rel_path
        if not src.exists():
            skipped_missing += 1
            continue

        subfolder = "debug" if is_debug else None
        dest = copy_artifact_to_run_dir(str(src), run_dir, subfolder=subfolder)
        if dest is None:
            print(f"  [WARN] Could not copy: {rel_path}")
            skipped_missing += 1
            continue

        file_hash = _hash_file_safe(src)
        register_run_artifact(
            db_path       = db_path,
            run_number    = 0,
            artifact_type = artifact_type,
            artifact_name = src.name,
            file_path     = dest,
            file_hash     = file_hash,
            format        = fmt,
        )
        registered += 1
        loc = f"debug/{src.name}" if is_debug else src.name
        print(f"  ✓ {loc:55s}  [{artifact_type}]")

    # ── Register report_memory.db as a REPORT_MEMORY input artifact ───────────
    rdb = root / "output" / "report_memory.db"
    if not rdb.exists():
        rdb = root / "data" / "report_memory.db"
    if rdb.exists():
        dest = copy_artifact_to_run_dir(str(rdb), run_dir)
        file_hash = _hash_file_safe(rdb)
        register_run_artifact(
            db_path       = db_path,
            run_number    = 0,
            artifact_type = "REPORT_MEMORY_DB",
            artifact_name = "report_memory.db",
            file_path     = dest or str(rdb),
            file_hash     = file_hash,
            format        = "sqlite",
        )
        registered += 1
        print(f"  ✓ {'report_memory.db':55s}  [REPORT_MEMORY_DB]")

    print(f"\n  Artifacts registered : {registered}")
    print(f"  Artifacts not found  : {skipped_missing}")

    # ── Register input provenance ─────────────────────────────────────────────
    print("\n  Registering input provenance ...")
    for rel_path, input_type, filename in _INPUT_CATALOG:
        src = root / rel_path
        file_hash = _hash_file_safe(src) if src.exists() else None
        register_run_input(
            db_path          = db_path,
            run_number       = 0,
            input_type       = input_type,
            source_filename  = filename,
            source_file_hash = file_hash,
            source_path      = str(src) if src.exists() else None,
        )
        input_count += 1
        status = "✓" if src.exists() else "— (not found)"
        print(f"  {status} Input [{input_type:8s}]: {filename}")

    # Register consultant report directory as a conceptual REPORT input
    report_dir = root / "input" / "consultant_reports"
    if report_dir.exists():
        pdf_files = sorted(report_dir.rglob("*.pdf"))
        pdf_count = len(pdf_files)
        register_run_input(
            db_path        = db_path,
            run_number     = 0,
            input_type     = "REPORT",
            source_filename= "consultant_reports/",
            source_file_hash=None,
            source_path    = str(report_dir),
            metadata_json  = json.dumps({"pdf_count": pdf_count}),
        )
        input_count += 1
        for pdf_path in pdf_files:
            register_run_input(
                db_path          = db_path,
                run_number       = 0,
                input_type       = "REPORT_FILE",
                source_filename  = pdf_path.name,
                source_file_hash = _hash_file_safe(pdf_path),
                source_path      = str(pdf_path),
            )
            input_count += 1
        print(f"  ✓ Input [REPORT  ]: consultant_reports/ ({pdf_count} PDFs)")

    # ── Step 5: Mark Run 0 as current ────────────────────────────────────────
    print("\n[5/5] Marking Run 0 as current ...")
    mark_run_current(db_path, 0)
    update_run_metadata(
        db_path,
        0,
        core_version="P1",
        summary_json=json.dumps(
            {
                "artifacts_registered": registered,
                "inputs_registered": input_count,
                "baseline_date": BASELINE_DATE,
            },
            sort_keys=True,
        ),
    )
    finalize_run_success(db_path, 0)
    invalidated = invalidate_descendant_runs(db_path, 0, "Baseline Run 0 rebuilt") if force else 0
    print("  Run 0 is now the current run.")
    if force:
        print(f"  Descendants marked stale: {invalidated}")

    # ── Summary ───────────────────────────────────────────────────────────────
    arts = list_run_artifacts(db_path, 0)
    print()
    print("=" * 64)
    print("BOOTSTRAP SUMMARY")
    print("=" * 64)
    print(f"  Run number        : 0")
    print(f"  Label             : {BASELINE_LABEL}")
    print(f"  Baseline date     : {BASELINE_DATE}")
    print(f"  Artifacts stored  : {len(arts)}")
    print(f"  Run folder        : {run_dir}")
    print(f"  DB                : {db_path}")
    print()
    print("  Run 0 is now the baseline truth.")
    print("  Future pipeline runs will derive from Run 0.")
    print("=" * 64)


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Bootstrap Run 0 from current trusted output state"
    )
    parser.add_argument(
        "--db-path", default=None,
        help="Path to run_memory.db (default: <root>/data/run_memory.db)",
    )
    parser.add_argument(
        "--root-dir", default=None,
        help="Project root directory (default: parent of scripts/)",
    )
    parser.add_argument(
        "--force", action="store_true",
        help="Re-bootstrap even if Run 0 already exists",
    )
    args = parser.parse_args()

    run_bootstrap_zero(
        db_path  = args.db_path,
        root_dir = args.root_dir,
        force    = args.force,
    )
