"""
bootstrap_report_memory.py
--------------------------
One-time (or re-runnable) script that seeds the persistent report memory DB
from already-existing historical outputs generated by consultant_integration.py.

Purpose:
  Previous pipeline runs already parsed and matched consultant PDFs into:
    output/consultant_match_report.xlsx

  This script reads those outputs and loads them into the SQLite DB so that
  future pipeline runs (main.py) can use report memory without needing to
  re-ingest the original PDFs.

Bootstrap sentinel hash:
  Because the original source PDFs may not be present at bootstrap time, we
  use a sentinel hash of the form:
      BOOTSTRAP::<rapport_id>
  This is clearly documented and distinct from real SHA-256 hashes.
  If the real PDF is found on disk, its actual SHA-256 is used instead.

Usage:
    cd "GF updater v3"
    python scripts/bootstrap_report_memory.py
    python scripts/bootstrap_report_memory.py --db-path data/report_memory.db
    python scripts/bootstrap_report_memory.py --root-dir /path/to/project

Output:
    Prints a summary:
        files scanned
        responses loaded
        reports registered
        duplicates skipped
"""

import argparse
import logging
import sys
from pathlib import Path

import pandas as pd

# ---------------------------------------------------------------------------
# Path setup — allows running from any working directory
# ---------------------------------------------------------------------------

_SCRIPT_DIR   = Path(__file__).resolve().parent          # scripts/
_PROJECT_ROOT = _SCRIPT_DIR.parent                        # GF updater v3/
_SRC_DIR      = _PROJECT_ROOT / "src"

sys.path.insert(0, str(_SRC_DIR))

from report_memory import (
    init_report_memory_db,
    sha256_file,
    is_report_already_ingested,
    register_ingested_report,
    upsert_report_responses,
    load_persisted_report_responses,
)

# ---------------------------------------------------------------------------
# Canonical source → approver mapping
# (mirrors consultant_matcher.CONSULTANT_CANONICAL)
# ---------------------------------------------------------------------------

# E2 confidence gate — only HIGH and MEDIUM rows enter the DB
_ELIGIBLE_CONFIDENCE_VALUES = {"HIGH", "MEDIUM"}


_SOURCE_TO_CANONICAL = {
    "LE_SOMMER":  "AMO HQE LE SOMMER",
    "LESOMMER":   "AMO HQE LE SOMMER",
    "AVLS":       "ACOUSTICIEN AVLS",
    "TERRELL":    "BET STR-TERRELL",
    "SOCOTEC":    "SOCOTEC",
    "BC_SOCOTEC": "SOCOTEC",
}


def _source_to_canonical(source: str) -> str:
    upper = source.upper().replace(" ", "_").replace("-", "_")
    for key, canonical in _SOURCE_TO_CANONICAL.items():
        if key in upper:
            return canonical
    return source  # fallback: keep as-is


# ---------------------------------------------------------------------------
# Bootstrap from consultant_match_report.xlsx
# ---------------------------------------------------------------------------

def _bootstrap_from_match_report(
    match_report_path: Path,
    consultant_reports_root: Path,
    db_path: str,
) -> dict:
    """
    Load matched consultant rows from consultant_match_report.xlsx and
    persist them into the report memory DB.

    Returns a summary dict:
        rows_total, rows_loaded, rows_skipped_dup, reports_registered,
        reports_already_ingested
    """
    if not match_report_path.exists():
        print(f"  [SKIP] Not found: {match_report_path}")
        return {
            "rows_total": 0, "rows_loaded": 0,
            "rows_skipped_dup": 0, "reports_registered": 0,
            "reports_already_ingested": 0,
        }

    print(f"  Loading: {match_report_path}")
    df = pd.read_excel(str(match_report_path))
    print(f"  Rows in file: {len(df)}")

    # Only process rows with a valid matched doc_id
    df = df[
        df["Matched GED doc_id"].notna() &
        (df["Matched GED doc_id"].astype(str).str.strip() != "")
    ].copy()
    print(f"  Rows with matched doc_id: {len(df)}")

    # Build a lookup: rapport_id → (source_filename, source_file_hash, report_type)
    # Hash the actual PDF if we can find it; else use sentinel.
    rapport_registry: dict = {}

    for rapport_id in df["Rapport ID"].unique():
        rapport_id_str = str(rapport_id).strip()
        if not rapport_id_str:
            continue

        # Try to find the PDF on disk by scanning input/consultant_reports/**
        pdf_hash = None
        pdf_found_path = None

        if consultant_reports_root.exists():
            for pdf_path in consultant_reports_root.rglob("*.pdf"):
                # Match: PDF stem starts with or contains the rapport_id
                if rapport_id_str in pdf_path.stem or rapport_id_str in pdf_path.name:
                    try:
                        pdf_hash = sha256_file(str(pdf_path))
                        pdf_found_path = pdf_path
                        break
                    except OSError:
                        pass

        if pdf_hash is None:
            # Use sentinel hash — clearly marked as bootstrap origin
            pdf_hash = f"BOOTSTRAP::{rapport_id_str}"

        rapport_registry[rapport_id_str] = {
            "source_filename": rapport_id_str,
            "source_file_hash": pdf_hash,
            "found_path": str(pdf_found_path) if pdf_found_path else None,
        }

    # ── Determine which rapport_ids are new (not yet in DB) ──────────────────
    new_rapport_ids: set = set()
    already_ingested_hashes: set = set()

    for rapport_id_str, info in rapport_registry.items():
        h = info["source_file_hash"]
        if is_report_already_ingested(db_path, h):
            already_ingested_hashes.add(h)
        else:
            new_rapport_ids.add(rapport_id_str)

    rows_skipped = sum(
        1 for _, row in df.iterrows()
        if str(row.get("Rapport ID", "")).strip() not in new_rapport_ids
    )

    # Filter to only new rows
    df_new = df[df["Rapport ID"].apply(
        lambda v: str(v).strip() in new_rapport_ids
    )].copy()

    if df_new.empty:
        print(f"  All {len(rapport_registry)} rapport_ids already ingested — nothing to add.")
        return {
            "rows_total": len(df),
            "rows_loaded": 0,
            "rows_skipped_dup": rows_skipped,
            "reports_registered": 0,
            "reports_already_ingested": len(already_ingested_hashes),
        }

    # ── Build responses DataFrame in the format expected by upsert_report_responses
    responses_records = []
    for _, row in df_new.iterrows():
        rapport_id_str = str(row.get("Rapport ID", "")).strip()
        if rapport_id_str not in rapport_registry:
            continue

        reg = rapport_registry[rapport_id_str]
        source_str = str(row.get("Consultant Source", "")).strip()

        responses_records.append({
            "consultant":           _source_to_canonical(source_str),
            "doc_id":               str(row.get("Matched GED doc_id", "")).strip(),
            "report_status":        str(row.get("STATUT_NORM", "") or "").strip() or None,
            "report_response_date": str(row.get("DATE_FICHE", "") or "").strip() or None,
            "report_comment":       str(row.get("COMMENTAIRE", "") or "").strip() or None,
            "source_filename":      reg["source_filename"],
            "source_file_hash":     reg["source_file_hash"],
            "match_confidence":     str(row.get("Confidence", "") or "").strip() or None,
            "match_method":         str(row.get("Match Method", "") or "").strip() or None,
        })

    if not responses_records:
        return {
            "rows_total": len(df),
            "rows_loaded": 0,
            "rows_skipped_dup": rows_skipped,
            "reports_registered": 0,
            "reports_already_ingested": len(already_ingested_hashes),
        }

    responses_df = pd.DataFrame(responses_records)

    # ── Gate E2 — confidence filter before upsert ─────────────────────────────
    # Block LOW / UNKNOWN / NULL confidence rows from entering the DB.
    before_e2 = len(responses_df)
    responses_df = responses_df[
        responses_df["match_confidence"].apply(
            lambda c: str(c).strip().upper() in _ELIGIBLE_CONFIDENCE_VALUES
            if c is not None else False
        )
    ].copy()
    blocked_e2 = before_e2 - len(responses_df)
    if blocked_e2:
        print(f"  E2 confidence gate: {blocked_e2} LOW/UNKNOWN rows blocked (not written to DB)")

    if responses_df.empty:
        print("  No eligible rows after confidence filter — nothing to upsert.")
        return {
            "rows_total": len(df),
            "rows_loaded": 0,
            "rows_skipped_dup": rows_skipped,
            "reports_registered": 0,
            "reports_already_ingested": len(already_ingested_hashes),
        }

    # ── Upsert responses into DB ──────────────────────────────────────────────
    rows_written = upsert_report_responses(db_path, responses_df)

    # ── Register each new rapport_id as an ingested report ───────────────────
    reports_registered = 0
    for rapport_id_str in new_rapport_ids:
        reg = rapport_registry[rapport_id_str]
        if reg["source_file_hash"] in already_ingested_hashes:
            continue  # race condition guard

        # Determine the report type from the source column
        matching_rows = df_new[df_new["Rapport ID"] == rapport_id_str]
        if matching_rows.empty:
            continue
        source_str = str(matching_rows.iloc[0].get("Consultant Source", "UNKNOWN")).strip()
        row_count  = len(matching_rows)

        is_sentinel = reg["source_file_hash"].startswith("BOOTSTRAP::")
        register_ingested_report(
            db_path          = db_path,
            report_type      = source_str,
            source_filename  = reg["source_filename"],
            source_file_hash = reg["source_file_hash"],
            row_count        = row_count,
            report_period    = None,
            status           = "INGESTED_BOOTSTRAP" if is_sentinel else "INGESTED",
        )
        reports_registered += 1

        loc_note = (
            f" (PDF found: {reg['found_path']})"
            if reg["found_path"]
            else " (PDF not found — sentinel hash used)"
        )
        print(f"    Registered: {rapport_id_str}{loc_note}")

    return {
        "rows_total": len(df),
        "rows_loaded": rows_written,
        "rows_skipped_dup": rows_skipped,
        "reports_registered": reports_registered,
        "reports_already_ingested": len(already_ingested_hashes),
    }


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def run_bootstrap(
    db_path: str | None = None,
    root_dir: str | None = None,
) -> None:
    logging.basicConfig(
        level=logging.WARNING,   # suppress library noise; we print our own summary
        format="%(levelname)s  %(message)s",
    )

    root = Path(root_dir).resolve() if root_dir else _PROJECT_ROOT
    if db_path is None:
        db_path = str(root / "data" / "report_memory.db")

    print("=" * 64)
    print("GF Updater V3 — Report Memory Bootstrap")
    print("=" * 64)
    print(f"  DB path    : {db_path}")
    print(f"  Root dir   : {root}")
    print()

    # ── Step 1: Initialise DB ─────────────────────────────────────────────────
    print("[1/3] Initialising report_memory.db ...")
    init_report_memory_db(db_path)
    print("  DB ready.")

    # ── Step 2: Bootstrap from consultant_match_report.xlsx ──────────────────
    print("\n[2/3] Scanning historical consultant outputs ...")
    match_report_path       = root / "output" / "consultant_match_report.xlsx"
    consultant_reports_root = root / "input"  / "consultant_reports"

    total_rows_loaded    = 0
    total_rows_skipped   = 0
    total_reports_reg    = 0
    total_already_ingest = 0
    files_scanned        = 0

    for label, path in [("consultant_match_report.xlsx", match_report_path)]:
        print(f"\n  File: {label}")
        if path.exists():
            files_scanned += 1
        result = _bootstrap_from_match_report(
            match_report_path       = path,
            consultant_reports_root = consultant_reports_root,
            db_path                 = db_path,
        )
        total_rows_loaded    += result["rows_loaded"]
        total_rows_skipped   += result["rows_skipped_dup"]
        total_reports_reg    += result["reports_registered"]
        total_already_ingest += result["reports_already_ingested"]

    # ── Step 3: Verification summary ─────────────────────────────────────────
    print("\n[3/3] Verification ...")
    loaded_df = load_persisted_report_responses(db_path)
    print(f"  Total persisted responses in DB: {len(loaded_df)}")
    if not loaded_df.empty:
        print(f"  Unique consultants : {loaded_df['consultant'].nunique()}")
        print(f"  Unique doc_ids     : {loaded_df['doc_id'].nunique()}")
        top_consultants = loaded_df["consultant"].value_counts().head(5)
        print("  Top consultants by row count:")
        for name, cnt in top_consultants.items():
            print(f"    {name}: {cnt}")

    print()
    print("=" * 64)
    print("BOOTSTRAP SUMMARY")
    print("=" * 64)
    print(f"  Files scanned              : {files_scanned}")
    print(f"  Responses loaded (new)     : {total_rows_loaded}")
    print(f"  Responses skipped (dup)    : {total_rows_skipped}")
    print(f"  Reports registered         : {total_reports_reg}")
    print(f"  Reports already in DB      : {total_already_ingest}")
    print(f"  Total in DB after bootstrap: {len(loaded_df)}")
    print("=" * 64)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Seed report_memory.db from existing consultant output files"
    )
    parser.add_argument(
        "--db-path", default=None,
        help="Path to report_memory.db (default: <root>/data/report_memory.db)",
    )
    parser.add_argument(
        "--root-dir", default=None,
        help="Project root directory (default: parent of scripts/)",
    )
    args = parser.parse_args()

    run_bootstrap(
        db_path  = args.db_path,
        root_dir = args.root_dir,
    )
